swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /Environment:
    get:
      operationId: "Environment.read"
      tags:
        - "Environment"
      summary: "The Environment data structure supported by the server application"
      description: "Read the list of Environment"
      responses:
        200:
          description: "Successful read environment list operation"
          schema:
            type: "array"
            items:
              properties:
                Temperture:
                  type: "string"
                Humidity:
                  type: "string"
                Pressure:
                  type: "string"