swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /Environmentfull:
    get:
      operationId: "Environmentfull.read"
      tags:
        - Enviroment
      summary: The enviroment data structure supported by the server application
      description: Read the list of environment
      responses:
        200:
          description: Successfully read enviroment list operation
          schema:
            type: "array"
            items:
              properties:
                Tem:
                  type: "string"
                Hum:
                  type: "string"
                Pre:
                  type: "string"
                Timestamp:
                  type: "string"
    put:
      operationId: Environmentfull.create
      tags:
        - Enviroment
      summary: Create a enviroment situation to the list
      description: Create a enviroment situation to the list
      parameters:
        - name: Enviroment
          in: body
          description: Enviroment to create
          required: True
          schema:
            type: object
            properties:
              Tem:
                type: string
                description: Temperture
              Hum:
                type: string
                description: Humidity
              Pre:
                type: string
                description: Pressure
      responses:
        201:
          description: Successfully created in list


  /Light:
    get:
      operationId: "Light.read"
      tags:
        - Light
      summary: The Light data structure supported by the server application
      description: Read the list of Light
      responses:
        200:
          description: Successfully read Light list operation
          schema:
            type: "array"
            items:
              properties:
                Light:
                  type: "string"
                State:
                  type: "string"
                Timestamp:
                  type: "string"
    put:
      operationId: Light.create
      tags:
        - Light
      summary: Create a Light situation to the list
      description: Create a Light situation to the list
      parameters:
        - name: Light
          in: body
          description: Light to create
          required: True
          schema:
            type: object
            properties:
              Light:
                type: string
                description: Light Light
              State:
                type: string
                description: Light State
      responses:
        201:
          description: Successfully created in list  
          
          
  /Fan:
    get:
      operationId: "Fan.read"
      tags:
        - Fan
      summary: The Fan data structure supported by the server application
      description: Read the list of Fan
      responses:
        200:
          description: Successfully read Fan list operation
          schema:
            type: "array"
            items:
              properties:
                Speed:
                  type: "string"
                State:
                  type: "string"
                Timestamp:
                  type: "string"
    put:
      operationId: Fan.create
      tags:
        - Fan
      summary: Create a Fan situation to the list
      description: Create a Fan situation to the list
      parameters:
        - name: Fan
          in: body
          description: Fan to create
          required: True
          schema:
            type: object
            properties:
              Speed:
                type: string
                description: Fan Speed
              State:
                type: string
                description: Fan State
      responses:
        201:
          description: Successfully created in list      
          

    
